### ISSUE TITLE
Make one registerBlock method instead of making two overloaded methods. 

### ISSUE THREAD

**Issue by adriankiezik** [hugeblank/endless_cake#1]
I think two methods of registerBlock methods are unnecesarry.

Also, is checking for "group == null" in first registerBlock required if there is second method to handle registering block without group?

**Comment by hugeblank** [comment]
you found my laziness :)

a lot of this code was ripped from [Bagels Baking](https://github.com/hugeblank/bagels_baking) where having two methods defined for registerBlock were necessary/helpful.

I have plans to add a few more features to it, I'll definitely refine the code when that happens, which will hopefully be soon.
